[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1
    -DESP32

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    adafruit/Adafruit MAX31856 library @ ^1.2.8
    adafruit/Adafruit BusIO @ ^1.17.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.4.1
